from django.shortcuts import get_object_or_404
from rest_framework import generics, permissions
from rest_framework.response import Response
from rest_framework.views import APIView

from .models import Notification
from .serializers import NotificationSerializer


class NotificationListView(generics.ListAPIView):
    """
    GET /notifications/ — the logged-in user's own alerts only.

    There is deliberately NO create endpoint (contract §5): notifications are
    system-generated by signal handlers, never by the frontend.
    """

    serializer_class = NotificationSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        return (
            Notification.objects.filter(recipient=self.request.user)
            .select_related('contribution')  # avoid N+1 on contribution_title
        )


class MarkNotificationReadView(APIView):
    """
    POST /notifications/{id}/read/ — owner-only, idempotent.

    Ownership is enforced by filtering on the recipient; other users'
    notifications 404 (not 403) so existence isn't leaked (contract §8).
    """

    permission_classes = [permissions.IsAuthenticated]

    def post(self, request, pk):
        notification = get_object_or_404(
            Notification, pk=pk, recipient=request.user
        )
        if not notification.is_read:
            notification.is_read = True
            notification.save(update_fields=['is_read'])
        return Response(NotificationSerializer(notification).data)
