"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from urllib.parse import unquote, urlparse
import sys

from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# No fallback: the app must fail to start rather than run with a publicly-known key.
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False so a forgotten env var can never leak details in production.
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

AUTH_USER_MODEL = 'users.User'

# Paystack settings
# No default: the secret key is the webhook HMAC key, so an empty value would
# let anyone forge a valid signature. Fail loudly instead, like SECRET_KEY above.
# The public key is only ever used by the frontend, so a missing value here is
# harmless and stays optional.
PAYSTACK_SECRET_KEY = config('PAYSTACK_SECRET_KEY')
PAYSTACK_PUBLIC_KEY = config('PAYSTACK_PUBLIC_KEY', default='')

# BMONI Embedded — the department's own NGN virtual bank account.
# Optional feature, so unlike PAYSTACK_SECRET_KEY the key is NOT required to
# boot: the app serves the Paystack flows fine without it. An empty key leaves
# the BMONI endpoints answering 503 (feature off) — never a fake account.
# The key travels in the `x-api-key` header (not Authorization) and is a PARTNER
# key: BMONI derives the partner from the key itself, so the now-deprecated
# `partnerId` body field is never sent.
# Base URL defaults to the shared sandbox. Production is
# https://embedded.bmoni.com and must be set explicitly in the environment.
BMONI_API_KEY = config('BMONI_API_KEY', default='')
BMONI_BASE_URL = config('BMONI_BASE_URL', default='https://embedded-dev.bmoni.com')
# The subscription's signing secret (BMONI's HMAC key). Empty => the webhook
# receiver fails closed (503) rather than trusting an unsigned delivery.
BMONI_WEBHOOK_SECRET = config('BMONI_WEBHOOK_SECRET', default='')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    # Local apps
    'apps.users',

    'apps.payments',

    'apps.contributions',

    'apps.notifications',

    'apps.analytics',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves STATIC_ROOT (incl. Django admin assets) without a separate server.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Local dev (and the demo) keep the plain SQLite file: with no DATABASE_URL env
# var the app uses db.sqlite3 — easy to inspect, back up and download. A
# production platform (Render) sets DATABASE_URL, e.g.
# postgres://user:pass@host:5432/dbname, and this same file switches to
# PostgreSQL. Parsed with the stdlib; only the psycopg2 driver is extra.
def _database_settings(database_url):
    """Translate DATABASE_URL into Django's DATABASES.default mapping."""
    if database_url.startswith('postgres'):
        # Hosted PostgreSQL (Render sets DATABASE_URL to postgres://...).
        db_parts = urlparse(database_url)
        return {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': db_parts.path.lstrip('/'),
            'USER': unquote(db_parts.username or ''),
            'PASSWORD': unquote(db_parts.password or ''),
            'HOST': db_parts.hostname or '',
            'PORT': db_parts.port or 5432,
            'CONN_MAX_AGE': 60,  # reuse connections; hosted Postgres dislikes connection storms
        }

    # SQLite file — the local dev/demo default (db.sqlite3 in backend/), also
    # chosen when DATABASE_URL points at sqlite:// or is unset.
    return {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }


database_url = config('DATABASE_URL', default='')

DATABASES = {
    'default': _database_settings(database_url),
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Test-only speed-up: hashing dominates runtime when many users are created
# per test (the full suite spent ~7 min mostly on PBKDF2). MD5 is fine for
# tests — no real credentials are ever stored there. Production is untouched.
if 'test' in sys.argv:
    PASSWORD_HASHERS = ['django.contrib.auth.hashers.MD5PasswordHasher']


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# collectstatic target for production (Django admin CSS/JS), served by
# whitenoise. Local runserver keeps serving straight from the apps.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Uploaded files (offline payment-proof screenshots). Served by Django only when
# DEBUG=True (see core/urls.py). A production host must put object storage or a
# static file server in front of MEDIA_ROOT.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',
    'DEFAULT_THROTTLE_RATES': {
        'auth': '10/min',
    },
    # DRF throttle identity. Unset/0 -> REMOTE_ADDR (correct for local dev,
    # which has no proxy). Behind Render's reverse proxy set NUM_PROXIES=1 so
    # the limiter reads the real client IP from X-Forwarded-For — otherwise
    # every student shares the proxy IP and the 10/min auth throttle locks the
    # whole school out at once.
    'NUM_PROXIES': int(config('NUM_PROXIES', default=0)),
}

# Explicit frontend origins (env-overridable for production). The real Vite
# dev server runs on 5173 (see dept-payments/vite.config.js) — 3000 is kept
# for other tooling.
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default=(
        'http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000'
    ),
    cast=Csv(),
)

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Logging: one console stream (the platform aggregates stdout). Root logger so
# every app — notably the Paystack webhook — leaves a forensic trail.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

