# Generated by Django 5.2.17 on 2026-09-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='is_closed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
