# Generated by Django 5.2.17 on 2026-09-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_contribution_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_status',
            field=models.CharField(choices=[('none', 'No refund due'), ('pending_review', 'Refund pending review'), ('refunded', 'Refunded'), ('rejected', 'Reviewed, no refund due')], db_index=True, default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('departmental_fee', 'Departmental Fee'), ('sports_jersey', 'Sports Jersey'), ('excursion', 'Excursion'), ('contribution', 'Contribution')], max_length=30),
        ),
    ]
