# Generated by Django 5.2.17 on 2026-09-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_paid_amount_payment_refund_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_reference',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
