# Generated by Django 5.2.17 on 2026-09-26 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_transaction_payment_unique_success_per_student_fee_and_more'),
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentBMONIWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_first_name', models.CharField(blank=True, default='', max_length=100)),
                ('holder_last_name', models.CharField(blank=True, default='', max_length=100)),
                ('holder_email', models.EmailField(blank=True, default='', max_length=254)),
                ('holder_phone', models.CharField(blank=True, default='', max_length=20)),
                ('holder_bvn_last4', models.CharField(blank=True, default='', max_length=4)),
                ('bmoni_user_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('bmoni_account_id', models.CharField(blank=True, default='', max_length=64)),
                ('account_name', models.CharField(blank=True, default='', max_length=150)),
                ('account_number', models.CharField(blank=True, default='', max_length=20)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('bank_code', models.CharField(blank=True, default='', max_length=20)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bmoni_wallet', to='users.department')),
            ],
        ),
        migrations.CreateModel(
            name='BMONIWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=128, unique=True)),
                ('event_type', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('raw_payload', models.JSONField()),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.departmentbmoniwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='departmentbmoniwallet',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'active'), _negated=True), models.Q(('account_number', ''), _negated=True), _connector='OR'), name='bmoni_active_wallet_has_account_number'),
        ),
    ]
