# Generated by Django 5.2.17 on 2026-10-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_departmentbmoniwallet_bmoniwebhookevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='channel',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='proofs/%Y/%m/'),
        ),
    ]
